### ISSUE TITLE
Command

### ISSUE THREAD

**Issue by Vadex-code** [justalemon/SimplePassive#106]
We put the Fxmanifest where it says to put on the website and it starts but when we get on server to run command nothing happens. we have the ace perms set up as well and the only issue is when we do /passivetoggle. nothing happens. it doesnt even pop up on list of commands when you start typing it

**Comment by justalemon** [comment]
Please post a picture of the simplepassive directory.

**Comment by Vadex-code** [comment]
[https://media.discordapp.net/attachments/715783947736449138/836701190242304000/unknown.png](url)

**Comment by Vadex-code** [comment]
![Simplepassivepicture](https://user-images.githubusercontent.com/73034391/116309070-8af85c80-a765-11eb-91e0-8bf96f439d67.png)

**Comment by justalemon** [comment]
Please reinstall with the instructions from https://github.com/justalemon/SimplePassive and select the .7z file, not the .zip or .tar.gz.
