### ISSUE TITLE
Still killable in passive/Melee still enabled

### ISSUE THREAD

**Issue by Based666** [justalemon/SimplePassive#108]
1. I've tested this script with others on a test server and found when a person is in passive mode (_which we checked because they were non-colliable while in a vehicle_), they can still be shot and melee killed while in a vehicle or on foot. 
2. While in the same session, we found that firearms could be pulled out but not shot (not the problem). However, when a passive or non-passive person pulls outs any melee weapon they could use it to harm other players _BUT_ only if they used **R** on a keyboard. Left-mouse click wouldn't use any weapon but **R** on keyboard would still use the weapon.
We tested this without any standalone scripts that affect anything related to combat, weapons, or other passive mode-like options. vMenu and a respawn script were enabled during this testing. Is there a vMenu permission making the script act this way? We have tested vMenu with weapons disabled but players could still use their fists to fight each other so it seems the weapon permissions didn't affect combat at all.

_Convars in server.cfg:_

setr simplepassive_default 1
setr simplepassive_alpha 255
setr simplepassive_disablecombat 1
setr simplepassive_debug 0
add_ace builtin.everyone simplepassive.changeself allow

**Comment by justalemon** [comment]
Can you try [this build](https://ci.appveyor.com/api/buildjobs/x7p2aqk3jjoj6ryy/artifacts/SimplePassive.7z) and let me know if it works?

You need to set the convar simplepassive_makeinvincible to 1, like this:

```
setr simplepassive_makeinvincible 1
```

**Comment by Based666** [comment]
> Can you try [this build](https://ci.appveyor.com/api/buildjobs/x7p2aqk3jjoj6ryy/artifacts/SimplePassive.7z) and let me know if it works?
> 
> You need to set the convar simplepassive_makeinvincible to 1, like this:
> 
> ```
> setr simplepassive_makeinvincible 1
> ```

I'll let you know as soon as I can get with my other testing buddy to check it with me.

**Comment by Based666** [comment]
So the new version fixed the invincibility and camera problems. Very thankful for this new version. I don't know if you're still working on the melee combat issue but it is still present in the newest version you sent out.

**Comment by justalemon** [comment]
> melee combat issue

The player is invincible,isn't it?

**Comment by Based666** [comment]
Only the players in passive mode are invincible but the passive mode players are able to kill non-passive players because R on keyboard/ O on controller still registers as a melee attack.

**Comment by justalemon** [comment]
That doesn't makes sense. Invincible is invincible. Plus, it was confirmed by someone else that the patch works.

Please make sure that you don't have other conflicting game scripts.

**Comment by Based666** [comment]
The passive mode players are still able to attack other non-passive players. That's what I'm trying to say. The invincibility works on players with passive enabled but they can still kill non-passive players because of the attacking problem.
I still have the same set up as before

**Comment by justalemon** [comment]
I think I have an idea why this happens. Ill post a new comment with the new build once I try to fix it.

**Comment by justalemon** [comment]
[Try this build](https://ci.appveyor.com/api/buildjobs/lkoj5der33431iv0/artifacts/SimplePassive.7z), it should disable the other controls that are used for melee.

**Comment by Based666** [comment]
The new version works like a charm! Thank you for being able to take the time to fix these problems.
