### ISSUE TITLE
Cooldown between toggles

### ISSUE THREAD

**Issue by Georgie15** [justalemon/SimplePassive#109]
You should add a 60 second cooldown between the toggle to prevent players from abusing it and getting out of scenes easily.

**Comment by justalemon** [comment]
There is now the simplepassive_cooldown convar, this sets the number of milliseconds seconds between each toggle.

![image](https://user-images.githubusercontent.com/11861253/235110175-7d74f608-6181-4743-99ab-76698a7f34f6.png)
