### ISSUE TITLE
Blocked file

### ISSUE THREAD

**Issue by ghost** [justalemon/SimplePassive#28]
The files are blocked and protected. I cannot modify them to give permission
![Screenshot_6](https://user-images.githubusercontent.com/65856945/83097771-d3fce800-a0a0-11ea-9375-896be6704ea3.png)

**Comment by justalemon** [comment]
Why would you edit the dll manually? Just use the [convars provided by the script](https://justalemon.ml/SimplePassive/Convars) on your server configuration.

**Comment by ghost** [comment]
Sorry, I did not understand the explanation
Can you explain to me how I can modify the file?

**Comment by justalemon** [comment]
If you want to modify the source code, clone this repo and build it.

If you want to configure the scripts, use the convars from the page that I posted.

**Comment by ghost** [comment]
It's good. I've set my own powers
But how can I get everyone to use this thing by default? They can not take out the weapons?
I apologize for the many questions

**Comment by justalemon** [comment]
Have you actually seen the convars page? Because there is this one that changes the default activations:

> ## simplepassive_default
> * Type: int
> * Default: 0
>
> The default activation status of Passive Mode. A value of 0 will disable passive mode for new players, while anything else will enable it by default.

**Comment by ghost** [comment]
It worked for me
I did not read the post well
I read it now and it worked for me
Thank you

**Comment by ghost** [comment]
Can I get some of my modifications for money?

**Comment by justalemon** [comment]
No. All of my projects are free under the MIT License for a reason.
