### ISSUE TITLE
Hit the player

### ISSUE THREAD

**Issue by ghost** [justalemon/SimplePassive#29]
Hello

I installed your script, but there is a problem when activated in the game other players can hit me and the player is not transparent only the vehicles are transparent, is there a way to be transparent when the option is enabled?

**Comment by justalemon** [comment]
Please, explain what settings do you have and what permissions you have enabled.

**Comment by ghost** [comment]
add_ace builtin.everyone simplepassive.changeself allow
setr simplepassive_default 1
setr simplepassive_alpha 500
setr simplepassive_disablecombat 1
setr simplepassive_debug 0

The only problem is that players can hit me while I'm in safe mode

**Comment by justalemon** [comment]
> the player is not transparent

> setr simplepassive_alpha 500

Do you at least know what you are doing? I'm being honest here, it appears that you don't know the alpha values accepted by the game.

**Comment by ghost** [comment]
I am not talking about this
I have raised the value to 1000
But the problem is that other players can hit me while I'm in the hidden position and I can't beat them
Is there a way that players can't beat me while I'm hidden?

**Comment by justalemon** [comment]
The alpha value is from 0 to 255, where lower values decrease the transparency of the entity.

For invincibility, you need to add it to your own script.

**Comment by Ya-Shun** [comment]
How to increase invincibility?

**Comment by justalemon** [comment]
I'm closing this issue because there were multiple questions that were not answered.

Feel free to open a new issue with a clear question.
